# Generated by Django 5.0.1 on 2025-03-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50)),
                ('title', models.TextField(max_length=40)),
                ('txt', models.TextField(max_length=1000)),
                ('datepublic', models.DateField(max_length=8)),
            ],
            options={
                'db_table': 'entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='xd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.TextField(max_length=10000)),
                ('txt', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='xd2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv2', models.TextField(max_length=10000)),
                ('txt2', models.TextField(max_length=10000)),
                ('aut2', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='xd3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv3', models.TextField(max_length=10000)),
                ('txt3', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='xd4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv4', models.TextField(max_length=10000)),
                ('txt4', models.TextField(max_length=10000)),
            ],
        ),
    ]
